# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# and https://github.com/lcolladotor/biocthis/blob/master/.github/workflows/check-bioc.yml
# and https://github.com/rformassspectrometry/QFeatures/blob/master/.github/workflows/check-bioc.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

name: check-bioc

env:
  bioc-version: 'RELEASE_3_15'
  
jobs:
  define-image:
    runs-on: ubuntu-latest
    outputs:
      biocv: ${{ env.bioc-version }}
      image: bioconductor/bioconductor_docker:${{ env.bioc-version }}
    steps:
      - run: echo "$bioc-version"
    
  R-CMD-check-bioc:
    name: ubuntu-latest (biocdocker ${{ needs.define-image.outputs.biocv }})
    runs-on: ubuntu-latest
    needs: [define-image]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    container:
      image: ${{ needs.define-image.outputs.image }}
      volumes: 
        - /home/runner/work/_temp/Library:/usr/local/lib/R/host-site-library
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install Linux system dependencies
        run: |
            sysreqs=$(Rscript -e 'cat("apt-get update -y && apt-get install -y", paste(gsub("apt-get install -y ", "", remotes::system_requirements("ubuntu", "20.04")), collapse = " "))')
            echo $sysreqs
            sudo -s eval "$sysreqs"
        
      - name: Query and install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Run R CMD check
        uses: r-lib/actions/check-r-package@v2
