on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

name: check-bioc

jobs:
  build-check: 
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os}} (${{ matrix.config.r }})
    container: 
      image: ${{ matrix.config.cont }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, r: '4.2', bioc: '3.16', cont: "bioconductor/bioconductor_docker:RELEASE_3_16", rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest" }
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RSPM: ${{ matrix.config.rspm }}
    steps:

      ## Set the R library to the directory matching the cache step
      ## (lcolladotor/biocthis)
      - name: Set R Library path on Linux
        if: runner.os == 'Linux'
        run: |
          mkdir /__w/_temp/Library
          echo ".libPaths('/__w/_temp/Library')" > ~/.Rprofile
          
          
      ## (r-lib/check-standard)
      - name: Checkout Repository
        uses: actions/checkout@v3
        
      ## (r-lib/check-standard) 
      - name: Query and install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      ## (r-lib/check-standard)
      - name: Check
        uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
