# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# and https://github.com/lcolladotor/biocthis/blob/master/.github/workflows/check-bioc.yml
# and https://github.com/rformassspectrometry/QFeatures/blob/master/.github/workflows/check-bioc.yml

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

name: check-bioc

env:
  bioc-version: 'RELEASE_3_15'
  
jobs:
  get-bioc-version:
    runs-on: ubuntu-latest
    outputs:
      biocv: ${{ env.bioc-version }}
    steps:
    
  R-CMD-check-bioc:
    name: ubuntu-latest (biocdocker ${{ needs.get-bioc-version.outputs.biocv }})
    runs-on: ubuntu-latest
    needs: [get-bioc-version]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    container:
      image: bioconductor/bioconductor_docker:${{ needs.get-bioc-version.outputs.biocv }}
      volumes: 
        - /home/runner/work/_temp/Library:/usr/local/lib/R/host-site-library
    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
